.github/pull_request_template.md
**Feature**: [GitHub Issue #17 ](https://github.com/lakinmindfire/PivotHead/issues/17)
- Add pull request template
-  NO
No 
Closes #17
=> chor:[17] Pull request template

BRANCHING.md
**Feature**: [GitHub Issue #17 ](https://github.com/lakinmindfire/PivotHead/issues/17)
- Test template for pull request
-  NO
No 
Closes #17
=> Feature/17 Pull request template test

packages/core/README.md
**Feature**: [GitHub Issue #31](https://github.com/lakinmindfire/PivotHead/issues/31)
-  Update in  README.md at `/packages/core`
no
no
No
No
Closes #31
=> bug:[31] Fix readme file

examples/vanilla-js-demo/README.md
This PR adds detailed instructions to the README.md for deploying the project using Vercel. It includes steps to install Vercel globally, log in, and deploy the project seamlessly using the Vercel CLI. These updates aim to simplify the deployment process for contributors and maintainers.
=> Add vercel deployment instructions to README.md

.husky/pre-commit, packages/core/src/__test__/aggregator.test.ts, packages/core/src/__test__/errors/BaseError.test.ts, packages/core/src/__test__/errors/InternalError.test.ts, packages/core/src/__test__/errors/ValidationError.test.ts, packages/core/src/engine/aggregator.ts, packages/core/src/errors/ErrorHandler.ts, packages/core/src/types/interfaces.ts
**Feature**: [GitHub Issue #43 ](https://github.com/mindfiredigital/PivotHead/issues/43)
- Update the pre-commit hook to include `pnpm test`, `pnpm lint`, and `pnpm build`.
- Update Husky configuration to run lint-staged.
- Tested by committing changes and verifying that the pre-commit hook runs all three commands.
No screenshots provided.
No preview required for this change.
After merging this PR, all developers should run `pnpm install` to ensure they have the latest Husky hooks installed.
Closes #33
=> feat:[43] Update command for pre-commit

examples/vanilla-js-demo/fieldsPopup.js, examples/vanilla-js-demo/header.js
This PR introduces a `Fields` popup triggered by the "Fields" button in the header. The popup allows users to manage fields in a pivot table by dragging them into sections (Report Filters, Columns, Rows, and Values).
- **HTML Structure**: Added a modal popup that contains sections for `All Fields`, `Report Filters`, `Columns`, `Rows`, and `Values`.
- **CSS Styling**: Styled the popup and its sections for a clean, responsive layout.
- **JavaScript Functionality**:
- Implemented drag-and-drop functionality for fields to be dragged into different sections (e.g., Report Filters, Columns).
- Added an event listener to handle the visibility of the popup (show/hide).
- Handled field population dynamically by adding fields to the available list.
- Integrated a close button (`×`) to hide the …
=> Add Fields Popup with Drag-and-Drop Functionality

examples/vanilla-js-demo/fieldsPopup.js
This pull request addresses the following issues and introduces new features in the Field Settings Popup:
1. **Fix functionality issue of Apply and Cancel buttons**: 
- Resolved issues with Apply and Cancel buttons not functioning correctly.
2. **Fix issue related to AllFields section not displaying content after opening the popup a second time**: 
- Fixed the issue preventing content from being shown in the AllFields section when reopening the popup.
3. **Add feature of dragging-back to AllFields section**: 
- Implemented the ability to drag fields back to the AllFields section from other sections (Values, Rows, Columns, Filters).
4. **Add aggregation button in Values section**: 
- Added an aggregation button to the Values section for providing aggregation options (Sum, Average, Count). …
=> feat:[57] Field settings popup bug fixes and features

examples/vanilla-js-demo/main.js
**Feature**: [GitHub Issue #59 ](https://github.com/mindfiredigital/PivotHead/issues/59)
-  Update main.js
- Remove sort controller and icons
- Improved data formatting for decimal values
- Add dollar sign for dollar value
- 
- No required.
[Live Preview](https://vanilla-js-demo-b6a4495tg-mfsisudhanshuks-projects.vercel.app/)
- Have a look on config for table
```
const config = {
data: data,
rows: [{ uniqueName: 'product', caption: 'Product' }],
columns: [{ uniqueName: 'region', caption: 'Region' }],
measures: [
{
uniqueName: 'sales',
caption: 'Total Sales',
aggregation: 'sum',
format: { 
type: 'currency', 
currency: 'USD',
locale: 'en-US',
decimals: 2
},
},
{
uniqueName: 'quantity',
caption: 'Total Quantity',
aggregation: 'sum',
format: { …
```
=> bug:[59] Improved UI and formating of data

examples/vanilla-js-demo/header.js, examples/vanilla-js-demo/main.js
**This PR addresses and resolves merge conflicts by:**
- Fixing issues in the merged code to ensure functionality remains intact.
1. Cleaning up redundant or unnecessary code introduced during the conflict resolution.
2. Validating that the final implementation aligns with project requirements and standards.
- Key Updates:
1. Removed duplicate and conflicting code blocks.
2. Streamlined logic to avoid redundancy.
3. Verified and tested affected modules for stability.
- Testing:
1. Manual testing performed to confirm no breakage in functionality.
=> Fix and Cleanup Code to Resolve Merge Conflicts

.github/workflows/publish.yml, README.md, package.json
**Add Deployoment workflow**
1. Automatically publish the package on npm on push in main branch .
2. Create artifact and realease version etc.
3. Update package name
4. Update package version to `v1.0.0` ref - https://semver.org/ .Check faq section.
5. Update keywords
6. Branch for versioning.
-  Key Changes:
1. Add github action inside .github/worklows/publish.yml
2. Update in package.json
=> Add CI/CD workflow for publishing on npm

README.md, examples/vanilla-js-demo/package.json, package.json, packages/core/README.md, packages/core/package.json, pnpm-lock.yaml
**Feature**: [GitHub Issue #00](https://github.com/mindfiredigital/PivotHead/issues/00)
-  Update the package name
[Add screenshots here]
- NOne
NOne
=> Update package name

.github/workflows/publish.yml
**Feature**: [GitHub Issue #00](https://github.com/mindfiredigital/PivotHead/issues/00)
- Change made for semantic release
No
- None
- 
NOne
=> Fix: Update workflow file

examples/vanilla-js-demo/package.json, package.json
We are facing issues with the current CI/CD workflows that need to be fixed to ensure seamless deployment of the `@mindfiredigital/pivothead-core` package to npm. The existing configurations need to be aligned with best practices for continuous integration, deployment automation, and handling the release pipeline to npm.
In addition to the CI/CD workflow improvements, the `package.json` files for both the `@pivothead/vanilla-js-demo` and `@mindfiredigital/pivothead-core` packages were updated to enhance the build process and improve deployment workflows.
- **Updated the `scripts` section**:
- `copy-core`: Copies the core UMD build (`pivothead-core.umd.js`) into the `lib` directory.
- `build`: Creates the `lib` directory and copies the core build for packaging.
- `start`: Runs a local …
=> fix: Fix issue related to publishing to npm

.github/workflows/publish.yml, package.json, pnpm-lock.yaml
This PR introduces a GitHub Actions workflow for automating the build and release process for the `@mindfiredigital/pivothead_core` package. The workflow has two main jobs: building the application and creating a GitHub release with semantic release automation and publishing to npm.
1. **Build Job**:
- Sets up Node.js and installs dependencies using `pnpm`.
- Builds the application using `pnpm run build`.
- Configures Git user information for the GitHub Actions bot.
2. **Create GitHub Release Job**:
- Runs after the build job, ensuring that the build completes successfully before the release step.
- Checks out the code again, installs `pnpm` and dependencies.
- Runs `semantic-release` to generate a GitHub release and publish the package to npm.
- Uploads the build artifacts (contents of …
=> fix: Add changes in semantic-release workflow

.github/workflows/publish.yml, .npmrc, .releaserc.json
This PR introduces several key updates for the deployment process of the `@mindfiredigital/pivothead_core` project. The changes include:
- Adding `.releaserc.json` for configuring semantic-release.
- Adding `.npmrc` for managing npm configuration.
- Updating the GitHub Actions workflow to automate builds, releases, and npm publishing.
- **Add `.releaserc.json`:** A configuration file for semantic-release, ensuring the correct automation of versioning, changelog generation, and release publishing.
- **Add `.npmrc`:** Provides necessary npm configuration settings for publishing the package.
- **Update `Deployment Workflow`:** 
- Introduced a build job to handle the build process using pnpm.
- Created a `create-github-release` job to handle the release generation and publishing to npm. …
=> Merge development to main branch 

.github/workflows/publish.yml, .releaserc.json
This PR updates the `publish.yml` GitHub Actions workflow to automate the process of building the project, creating a GitHub release, and publishing the package to npm. The workflow now integrates `semantic-release` to handle versioning and publishing. It also ensures that the build is packaged and uploaded as an artifact for future reference.
1. **Build Job (`build`)**:
- Sets up Node.js 20.x using `actions/setup-node@v4`.
- Installs dependencies using `pnpm`.
- Builds the application using `pnpm run build`.
- Configures Git user details for commit and release generation.
2. **Create GitHub Release and Publish to NPM Job (`create-github-release`)**:
- Runs after the `build` job (`needs: build`).
- Uses `npx semantic-release` to handle automatic versioning, changelog generation, and …
=> fix: Add changes in publish.yml

.github/workflows/publish.yml
---
This PR updates the `publish.yml` GitHub Actions workflow to automate the process of building the package, creating a GitHub release, and publishing the package to NPM. The workflow is triggered by pushes to the `main` branch or manually via `workflow_dispatch`.
---
1. **Install `pnpm` globally**:
- Added a step to install `pnpm` globally in both the `build` and `create-github-release` jobs to ensure `pnpm` is available for installing dependencies and running build scripts.
2. **Build the application**:
- The `build` job installs dependencies using `pnpm` and then builds the application with `pnpm run build`.
3. **Run `semantic-release`**:
- The `create-github-release` job includes a step to run `semantic-release`, which handles the versioning, changelog generation, GitHub release …
=> Update the publish.yml for automation

BRANCHING.md, COMMIT_MESSAGE.md, pre-commit-validation.sh
**Feature**: [GitHub Issue #73](https://github.com/mindfiredigital/PivotHead/issues/73)
-  Add patch type to branch and commit message validation for quick fixes.
None
None
None
Closes #73
=> docs:[73] Update branching naming convention

README.md
**Feature**: [GitHub Issue #98](https://github.com/mindfiredigital/PivotHead/issues/98)
- Update `readme.md` 
None
- None
- None
Closes #13
=> docs:[98] Update readme header

examples/new/package.json, examples/sample-project/package.json
feat(core): fix unwanted private true
=> feat(core): fix unwanted private true

examples/pivothead-default-demo/README.md, examples/pivothead-default-demo/index.html, examples/pivothead-default-demo/vite.config.js, examples/simple-js-demo/index.js, packages/core/src/__test__/pivotEngine.test.ts, packages/core/src/engine/pivotEngine.ts, packages/web-component/package.json, packages/web-component/src/__test__/pivotHead.test.ts, packages/web-component/src/pivot-head/pivotHead.ts, packages/web-component/vitest.config.ts
- Added default mode rendering for <pivot-head> web component
- Created  example in  folder
- Completed example testing and verified functionality
- Improved core engine logic and updated unit tests
- Fixed linting and TypeScript errors in web component package
This pull request addresses the following issue: 
**Feature**: [GitHub Issue #<167>](https://github.com/mindfiredigital/PivotHead/issues/167)
- [List the main changes implemented]
[Add screenshots here]
- [Describe how the feature was tested]
[Add any additional information or context about the pull request here]
[Provide preview url(if available)]
Closes #<issue_number>
=> feat(web-component): implement default <pivot-head> with Shadow DOM

documentation/docs/contributors/contributors.md, documentation/docs/tutorial-basics/web-component.md, documentation/docs/tutorial-basics/wrappers/react.md, documentation/docs/tutorial-basics/wrappers/vue.md
**Feature**: [GitHub Issue #185](https://github.com/mindfiredigital/PivotHead/issues/185)
- [Addd Documentation for wrapper(React, Vue) and web-component]
[Add screenshots here]
=> docs(docs): add documentation for React, Vue, and web-component

pnpm-lock.yaml
**Feature**: [GitHub Issue #<issue_number>](https://github.com/mindfiredigital/PivotHead/issues/<issue_number>)
- [List the main changes implemented]
[Add screenshots here]
- [Describe how the feature was tested]
[Add any additional information or context about the pull request here]
[Provide preview url(if available)]
Closes #<issue_number>
=> chore(core): update lockfile

documentation/src/components/dataVisualisation.tsx, documentation/src/pages/index.js, documentation/src/pages/index.module.css
=> docs(core): modify the landing page for mobile responsive
